"""Creates `user_settings` table.

Revision ID: 2c8d70452315
Revises: 763bcb819b1f
Create Date: 2024-05-15 14:12:07.743556

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2c8d70452315"
down_revision: str | None = "763bcb819b1f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("en", "ru", "uk", name="user_language").create(op.get_bind())
    op.create_table(
        "user_settings",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "language",
            postgresql.ENUM("en", "ru", "uk", name="user_language", create_type=False),
            server_default=sa.text("'en'"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_user_settings_language"), "user_settings", ["language"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_settings_language"), table_name="user_settings")
    op.drop_table("user_settings")
    sa.Enum("en", "ru", "uk", name="user_language").drop(op.get_bind())
    # ### end Alembic commands ###
