"""create users table

Revision ID: 30024b96ee2a
Revises: 4eabf72ee590
Create Date: 2024-05-16 19:42:51.334871

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "30024b96ee2a"
down_revision: str | None = "4eabf72ee590"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("en", "ru", "uk", name="user_language").create(op.get_bind())
    op.create_table(
        "users",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("telegram_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "language",
            postgresql.ENUM("en", "ru", "uk", name="user_language", create_type=False),
            server_default=sa.text("'en'"),
            nullable=False,
        ),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_language"), "users", ["language"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_language"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    sa.Enum("en", "ru", "uk", name="user_language").drop(op.get_bind())
    # ### end Alembic commands ###
