"""Creates `adverts` table.

Revision ID: 6e8a466731d5
Revises: caa3c3c8869a
Create Date: 2024-09-29 20:02:13.349726

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e8a466731d5"
down_revision: str | None = "caa3c3c8869a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adverts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("monitoring_id", sa.BigInteger(), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column("image", sa.String(length=2000), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("max_price", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["monitoring_id"],
            ["monitorings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("monitoring_id", "url"),
    )
    op.create_index(op.f("ix_adverts_created_at"), "adverts", ["created_at"], unique=False)
    op.create_index(op.f("ix_adverts_monitoring_id"), "adverts", ["monitoring_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_adverts_monitoring_id"), table_name="adverts")
    op.drop_index(op.f("ix_adverts_created_at"), table_name="adverts")
    op.drop_table("adverts")
    # ### end Alembic commands ###
