"""Creates `monitorings` table.

Revision ID: 78262223d113
Revises: bb1b27229e64
Create Date: 2024-09-29 19:41:10.664782

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78262223d113"
down_revision: str | None = "bb1b27229e64"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monitorings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("marketplace_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("run_interval", sa.Interval(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["marketplace_id"],
            ["marketplaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "url"),
    )
    op.create_index(op.f("ix_monitorings_created_at"), "monitorings", ["created_at"], unique=False)
    op.create_index(op.f("ix_monitorings_marketplace_id"), "monitorings", ["marketplace_id"], unique=False)
    op.create_index(op.f("ix_monitorings_run_interval"), "monitorings", ["run_interval"], unique=False)
    op.create_index(op.f("ix_monitorings_user_id"), "monitorings", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_monitorings_user_id"), table_name="monitorings")
    op.drop_index(op.f("ix_monitorings_run_interval"), table_name="monitorings")
    op.drop_index(op.f("ix_monitorings_marketplace_id"), table_name="monitorings")
    op.drop_index(op.f("ix_monitorings_created_at"), table_name="monitorings")
    op.drop_table("monitorings")
    # ### end Alembic commands ###
