"""add uk language

Revision ID: a56adf4ac6a3
Revises: d75bc203c65d
Create Date: 2025-01-04 18:10:25.966511

"""

# mypy: disable-error-code="attr-defined"
# pylint: disable=R0801

from typing import Sequence

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "a56adf4ac6a3"
down_revision: str | None = "d75bc203c65d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="user_language",
        new_values=["en", "ru", "uk"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="users",
                column_name="language",
                existing_server_default="'en'::user_language",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="user_language",
        new_values=["en", "ru"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="users",
                column_name="language",
                existing_server_default="'en'::user_language",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
