"""Creates `monitorings` table.

Revision ID: a5ec1d44761d
Revises: c424bd2fd961
Create Date: 2024-07-21 19:11:59.770502

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a5ec1d44761d"
down_revision: str | None = "c424bd2fd961"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("olx_ua", name="marketplace").create(op.get_bind())
    op.create_table(
        "monitorings",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("marketplace", postgresql.ENUM("olx_ua", name="marketplace", create_type=False), nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("url", sa.VARCHAR(length=1000), nullable=False),
        sa.Column("run_interval", postgresql.INTERVAL(), nullable=False),
        sa.Column("enabled", sa.BOOLEAN(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "url"),
    )
    op.create_index(op.f("ix_monitorings_created_at"), "monitorings", ["created_at"], unique=False)
    op.create_index(op.f("ix_monitorings_enabled"), "monitorings", ["enabled"], unique=False)
    op.create_index(op.f("ix_monitorings_marketplace"), "monitorings", ["marketplace"], unique=False)
    op.create_index(op.f("ix_monitorings_run_interval"), "monitorings", ["run_interval"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_monitorings_run_interval"), table_name="monitorings")
    op.drop_index(op.f("ix_monitorings_marketplace"), table_name="monitorings")
    op.drop_index(op.f("ix_monitorings_enabled"), table_name="monitorings")
    op.drop_index(op.f("ix_monitorings_created_at"), table_name="monitorings")
    op.drop_table("monitorings")
    sa.Enum("olx_ua", name="marketplace").drop(op.get_bind())
    # ### end Alembic commands ###
