"""Creates `monitoring_runs` table.

Revision ID: ae9c787ed9a4
Revises: a5ec1d44761d
Create Date: 2024-07-21 19:27:18.085767

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ae9c787ed9a4"
down_revision: str | None = "a5ec1d44761d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("scheduled", "running", "success", "failed", name="run_status").create(op.get_bind())
    op.create_table(
        "monitoring_runs",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("monitoring_id", sa.BIGINT(), nullable=False),
        sa.Column("log_file", sa.VARCHAR(length=100), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("scheduled", "running", "success", "failed", name="run_status", create_type=False),
            server_default=sa.text("'scheduled'"),
            nullable=False,
        ),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["monitoring_id"],
            ["monitorings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_monitoring_runs_created_at"), "monitoring_runs", ["created_at"], unique=False)
    op.create_index(op.f("ix_monitoring_runs_status"), "monitoring_runs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_monitoring_runs_status"), table_name="monitoring_runs")
    op.drop_index(op.f("ix_monitoring_runs_created_at"), table_name="monitoring_runs")
    op.drop_table("monitoring_runs")
    sa.Enum("scheduled", "running", "success", "failed", name="run_status").drop(op.get_bind())
    # ### end Alembic commands ###
