"""Creates `monitorings` table.

Revision ID: c7667811799f
Revises: 30024b96ee2a
Create Date: 2024-05-16 20:52:31.769087

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c7667811799f"
down_revision: str | None = "30024b96ee2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monitorings",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("marketplace_id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("url", sa.VARCHAR(length=1000), nullable=False),
        sa.Column("run_interval", postgresql.INTERVAL(), nullable=False),
        sa.Column("enabled", sa.BOOLEAN(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["marketplace_id"],
            ["marketplaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "url"),
    )
    op.create_index(op.f("ix_monitorings_created_at"), "monitorings", ["created_at"], unique=False)
    op.create_index(op.f("ix_monitorings_enabled"), "monitorings", ["enabled"], unique=False)
    op.create_index(op.f("ix_monitorings_run_interval"), "monitorings", ["run_interval"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_monitorings_run_interval"), table_name="monitorings")
    op.drop_index(op.f("ix_monitorings_enabled"), table_name="monitorings")
    op.drop_index(op.f("ix_monitorings_created_at"), table_name="monitorings")
    op.drop_table("monitorings")
    # ### end Alembic commands ###
