"""Creates `adverts` table.

Revision ID: cc9f52583b41
Revises: ae9c787ed9a4
Create Date: 2024-07-21 19:30:40.595143

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cc9f52583b41"
down_revision: str | None = "ae9c787ed9a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adverts",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("monitoring_id", sa.BIGINT(), nullable=False),
        sa.Column("external_id", sa.VARCHAR(length=100), nullable=False),
        sa.Column("url", sa.VARCHAR(length=1000), nullable=False),
        sa.Column("image", sa.VARCHAR(length=1000), nullable=True),
        sa.Column("title", sa.VARCHAR(length=100), nullable=False),
        sa.Column("description", sa.VARCHAR(length=200), nullable=True),
        sa.Column("price", sa.FLOAT(), nullable=True),
        sa.Column("max_price", sa.FLOAT(), nullable=True),
        sa.Column("currency", sa.VARCHAR(length=3), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["monitoring_id"],
            ["monitorings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("monitoring_id", "external_id"),
    )
    op.create_index(op.f("ix_adverts_created_at"), "adverts", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_adverts_created_at"), table_name="adverts")
    op.drop_table("adverts")
    # ### end Alembic commands ###
