"""add ru language

Revision ID: d75bc203c65d
Revises: 9d1e9c088371
Create Date: 2025-01-04 14:17:17.761860

"""

# mypy: disable-error-code="attr-defined"

from typing import Sequence

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "d75bc203c65d"
down_revision: str | None = "9d1e9c088371"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="user_language",
        new_values=["en", "ru"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="users",
                column_name="language",
                existing_server_default="'en'::user_language",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="user_language",
        new_values=["en"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="users",
                column_name="language",
                existing_server_default="'en'::user_language",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
