x-postgres-common:
  &postgres-common
  image: postgres:17.0
  environment:
    - POSTGRES_USER=${DATABASE_USER}
    - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    - POSTGRES_DB=${DATABASE_NAME}
  volumes:
    - ./docker_volumes/postgres:/var/lib/postgresql/data
  healthcheck:
    test: ["CMD", "pg_isready", "-U", "${DATABASE_USER}"]
    interval: 10s
    retries: 5
    start_period: 5s
  restart: always


services:
  postgres-dev:
    <<: *postgres-common
    profiles:
      - dev
    ports:
      - "${DATABASE_PORT}:5432"

  postgres:
    <<: *postgres-common
