"""Creates `adverts` table.

Revision ID: 338fd2685515
Revises: '4e958f8d945f'
Create Date: 2023-12-26 14:19:24.945223

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from database.queries import CREATE_UPDATED_AT_TRIGGER

# revision identifiers, used by Alembic.
revision: str = "338fd2685515"
down_revision: str | None = "4e958f8d945f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# pylint: disable=R0801
def upgrade() -> None:
    """Upgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adverts",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("search_query_id", sa.BIGINT(), nullable=False),
        sa.Column("external_id", sa.VARCHAR(length=100), nullable=False),
        sa.Column("url", sa.VARCHAR(length=1000), nullable=False),
        sa.Column("image", sa.VARCHAR(length=1000), nullable=True),
        sa.Column("title", sa.VARCHAR(length=1000), nullable=False),
        sa.Column("description", sa.VARCHAR(length=200), nullable=True),
        sa.Column("value", sa.FLOAT(), nullable=True),
        sa.Column("max_value", sa.FLOAT(), nullable=True),
        sa.Column("currency", sa.VARCHAR(length=3), nullable=True),
        sa.Column("status", sa.SMALLINT(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.ForeignKeyConstraint(
            ["search_query_id"],
            ["search_queries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("search_query_id", "external_id", name="ix_adverts_search_query_id_external_id"),
    )
    op.create_index(op.f("ix_adverts_created_at"), "adverts", ["created_at"], unique=False)
    op.create_index(op.f("ix_adverts_status"), "adverts", ["status"], unique=False)
    op.create_index(op.f("ix_adverts_updated_at"), "adverts", ["updated_at"], unique=False)
    op.execute(CREATE_UPDATED_AT_TRIGGER.format(table="adverts"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_adverts_updated_at"), table_name="adverts")
    op.drop_index(op.f("ix_adverts_status"), table_name="adverts")
    op.drop_index(op.f("ix_adverts_created_at"), table_name="adverts")
    op.drop_table("adverts")
    # ### end Alembic commands ###
