"""Creates `search_tasks` table.

Revision ID: 4e958f8d945f
Revises: '4f32c9f5092e'
Create Date: 2023-12-26 14:09:02.368019

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from database.queries import CREATE_UPDATED_AT_TRIGGER

# revision identifiers, used by Alembic.
revision: str = "4e958f8d945f"
down_revision: str | None = "4f32c9f5092e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_tasks",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("search_query_id", sa.BIGINT(), nullable=False),
        sa.Column("log_file", sa.VARCHAR(length=100), nullable=True),
        sa.Column("statistics", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.SMALLINT(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.ForeignKeyConstraint(
            ["search_query_id"],
            ["search_queries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_search_tasks_created_at"), "search_tasks", ["created_at"], unique=False)
    op.create_index(op.f("ix_search_tasks_status"), "search_tasks", ["status"], unique=False)
    op.create_index(op.f("ix_search_tasks_updated_at"), "search_tasks", ["updated_at"], unique=False)
    op.execute(CREATE_UPDATED_AT_TRIGGER.format(table="search_tasks"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_search_tasks_updated_at"), table_name="search_tasks")
    op.drop_index(op.f("ix_search_tasks_status"), table_name="search_tasks")
    op.drop_index(op.f("ix_search_tasks_created_at"), table_name="search_tasks")
    op.drop_table("search_tasks")
    # ### end Alembic commands ###
