"""Creates `search_queries` table.

Revision ID: 4f32c9f5092e
Revises: '8c95db9b5165'
Create Date: 2023-12-26 13:51:20.183541

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from database.queries import CREATE_UPDATED_AT_TRIGGER

# revision identifiers, used by Alembic.
revision: str = "4f32c9f5092e"
down_revision: str | None = "8c95db9b5165"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_queries",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("url", sa.VARCHAR(length=766), nullable=False),
        sa.Column("marketplace", sa.VARCHAR(length=20), nullable=False),
        sa.Column("last_crawl_time", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("crawl_interval", sa.SMALLINT(), nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), server_default=sa.text("TRUE"), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "url", name="ix_search_queries_user_id_url"),
    )
    op.create_index(op.f("ix_search_queries_created_at"), "search_queries", ["created_at"], unique=False)
    op.create_index(op.f("ix_search_queries_updated_at"), "search_queries", ["updated_at"], unique=False)
    op.execute(CREATE_UPDATED_AT_TRIGGER.format(table="search_queries"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_search_queries_updated_at"), table_name="search_queries")
    op.drop_index(op.f("ix_search_queries_created_at"), table_name="search_queries")
    op.drop_table("search_queries")
    # ### end Alembic commands ###
