"""Creates `users` table.

Revision ID: 8c95db9b5165
Revises: None
Create Date: 2023-12-26 13:11:33.568347

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from database.queries import (
    CREATE_REFRESH_UPDATED_AT_FUNC,
    CREATE_UPDATED_AT_TRIGGER,
    DROP_REFRESH_UPDATED_AT_FUNC,
)

# revision identifiers, used by Alembic.
revision: str = "8c95db9b5165"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=500), nullable=False),
        sa.Column("language", sa.VARCHAR(length=2), server_default=sa.text("'en'"), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_updated_at"), "users", ["updated_at"], unique=False)
    op.execute(CREATE_REFRESH_UPDATED_AT_FUNC)
    op.execute(CREATE_UPDATED_AT_TRIGGER.format(table="users"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_updated_at"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.execute(DROP_REFRESH_UPDATED_AT_FUNC)
    # ### end Alembic commands ###
