name: Build and lint

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: docker build --build-arg POETRY_INSTALL_DEV=True -t marketplace-monitoring-bot:tmp .

    - name: Lint
      run: docker run marketplace-monitoring-bot:tmp poetry run bash ./scripts/lint.sh
