name: Code quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    name: Build and lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build image
      run: docker build --build-arg POETRY_INSTALL_DEV=True -t marketplace-monitoring-bot .

    - name: Lint code
      run: docker run marketplace-monitoring-bot poetry run bash ./scripts/lint.sh
